# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch


# Create random tensor
random_tensor = torch.randn(7, 7)
print(random_tensor)
print(random_tensor.shape)
print(random_tensor.ndim)

tensor([[ 0.1756, -1.0372,  0.4203,  1.2304, -0.9854,  0.3409, -0.2091],
        [ 0.0202,  0.0699,  0.2492, -0.4444, -0.3861,  1.7151, -1.5033],
        [-1.1510,  0.7799, -0.5900, -2.3654, -0.8748, -1.3190, -0.2534],
        [ 0.0270,  0.0829,  0.5170,  1.7555,  0.1558, -0.5638,  0.0473],
        [-0.2670,  1.3412,  0.6579, -0.4207, -0.1331,  1.8016,  1.4834],
        [ 0.9266,  0.4445, -0.4569,  0.9958,  0.7175,  0.5676, -1.5967],
        [-1.1189, -1.2983,  0.3697, -2.2635, -0.1008, -1.0740,  0.3626]])
torch.Size([7, 7])
2


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
another_random_tensor = torch.randn(1, 7)
another_random_tensor = torch.transpose(another_random_tensor, 0, 1)
print(another_random_tensor)
# Perform matrix multiplication 
matrix_multiplication = torch.matmul(random_tensor, another_random_tensor)
print(matrix_multiplication)

tensor([[ 2.1814],
        [-2.1791],
        [ 0.1712],
        [-0.8441],
        [ 1.8050],
        [ 1.5185],
        [-0.4971]])
tensor([[ 7.6404],
        [-0.0154],
        [ 5.6161],
        [ 0.9497],
        [ 7.0217],
        [ 2.3592],
        [-9.9679]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [12]:
# Set manual seed
manual_seed_0 = torch.manual_seed(0)

# Create two random tensors
tensor_random_1 = torch.randn(7, 7)
tensor_random_2 = torch.randn(1, 7)
# Matrix multiply tensors
tensor_m = torch.matmul(tensor_random_1, torch.transpose(tensor_random_2, 0, 1))
print(tensor_m)
print(tensor_m.shape)

tensor([[ 3.5168],
        [ 2.1984],
        [-1.7815],
        [ 3.8600],
        [-1.5010],
        [-1.6916],
        [-2.9352]])
torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [3]:
# Set random seed on the GPU

# 检查GPU是否可用
if torch.cuda.is_available():
    # 设置单GPU随机种子（核心）
    torch.cuda.manual_seed(1234)
    # 若有多块GPU，需设置所有GPU的种子
    torch.cuda.manual_seed_all(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [3]:
# Set random seed
# Check for access to GPU
if torch.cuda.is_available():
    device = torch.device("cuda:0")
    torch.cuda.manual_seed(1234)
# Create two random tensors on GPU
    tensor_random_g_1 = torch.rand(2,3,device=device)
    tensor_random_g_2 = torch.rand(2,3,device=device)
    print(tensor_random_g_1)
    print(tensor_random_g_2)

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [4]:
# Perform matmul on tensor_A and tensor_B
print(torch.matmul(tensor_random_g_1, torch.transpose(tensor_random_g_2, 0, 1)))

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [5]:
# Find max
print(torch.matmul(tensor_random_g_1, torch.transpose(tensor_random_g_2, 0, 1)).max())
# Find min
print(torch.matmul(tensor_random_g_1, torch.transpose(tensor_random_g_2, 0, 1)).min())

tensor(0.7668, device='cuda:0')
tensor(0.2786, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [6]:
# Find arg max
print(torch.matmul(tensor_random_g_1, torch.transpose(tensor_random_g_2, 0, 1)).argmax())

# Find arg min
print(torch.matmul(tensor_random_g_1, torch.transpose(tensor_random_g_2, 0, 1)).argmin())

tensor(1, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

创建一个形状为 (1, 1, 1, 10) 的随机张量，然后创建一个新张量 —— 移除所有尺寸为 1 的维度，最终得到形状为 (10) 的张量。创建随机张量时将随机种子设置为 7，并打印第一个张量及其形状，以及第二个张量及其形状。

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed
torch.cuda.manual_seed(7)
device = torch.device("cuda:0")

# Create random tensor
tensor_random_g_seed7 = torch.randn(1,1,1,10,device=device)

# Remove single dimensions
tensor_random_g_seed7_squ = tensor_random_g_seed7.squeeze()

# Print out tensors and their shapes
print(tensor_random_g_seed7)
print(tensor_random_g_seed7.shape)
print(tensor_random_g_seed7_squ)
print(tensor_random_g_seed7_squ.shape)

tensor([[[[-0.3048,  1.0453, -0.2786,  0.7178, -0.7942, -1.1229, -0.8033,
           -1.0097,  0.6302, -0.2872]]]], device='cuda:0')
torch.Size([1, 1, 1, 10])
tensor([-0.3048,  1.0453, -0.2786,  0.7178, -0.7942, -1.1229, -0.8033, -1.0097,
         0.6302, -0.2872], device='cuda:0')
torch.Size([10])
